#######
# Compiled from test.mcscript
# to test.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set raycast1 mcscript_raycast 0
execute positioned ~ ~1 ~ run function noname:mcscript/raycast1
