#######
# Compiled from test.mcscript
# to mcscript/foreach1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation result result *= i i
scoreboard players add i i 1
execute if entity @s[tag=!mcscriptStop] if score i i matches ..10 run function noname:mcscript/foreach1
tag @s[tag=mcscriptStop] remove mcscriptStop
